import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:foodzilla/models/restaurant_model.dart';
import 'package:foodzilla/providers/date_time_provider.dart';
import 'package:foodzilla/providers/restaurant_detail_provider.dart';
import 'package:foodzilla/providers/restaurant_provider.dart';
import 'package:foodzilla/screens/screens.dart';
import 'package:foodzilla/services/services.dart';
import 'package:foodzilla/shared/constants.dart';
import 'package:provider/provider.dart';
import 'package:foodzilla/providers/theme_provider.dart';

part 'restaurant_card.dart';
part 'auth_input.dart';
part 'favourite_restaurant_widget.dart';
part 'restaurants_list.dart';
part 'date_time_widget.dart';
part 'favourite_icon_widget.dart';
